name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:"/home/runner/work/TEST/TEST/methods"
          export PYTHONPATH=$PYTHONPATH:"/home/runner/work/TEST/TEST/resources"
          pip install pytest
          pytest
