name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Run tests
        run: |
          export PYTHONPATH=’/home/runner/work/TEST/TEST/methods/circle.py’
          export PYTHONPATH=’/home/runner/work/TEST/TEST/methods/rectangle.py’
          export PYTHONPATH=’/home/runner/work/TEST/TEST/methods/square.py’
          export PYTHONPATH=’/home/runner/work/TEST/TEST/methods/triangle.py’
          pip install pytest
          pytest

  test_windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@main
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Run tests
        run: |
          tests/test_start.py
