name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Run tests
        run: |
          $env:PYTHONPATH='D:\a\TEST\TEST\methods;D:\a\TEST\TEST\resources'
          pip install pytest
          pytest
