name: CI

on:
  push:
    branches: [ main/master ]

jobs:
  run_tests:
    runs-on: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      
      - name: Run tests
        run: tests/tests_start.py
